### ISSUE TITLE
As a logged in user a new shopping list could be provided

### ISSUE THREAD

**Issue by Bl4ck4** [t-persson/mira#16]
A shopping list could be created maybe by choosing some recipes in the app and then check what is in the fridge already. If items are missing these could be added to a shopping list.
- [ ] Shopping list frontend
- [ ] Shopping list backend - t-persson/babylon#3
- [ ] Button to add ingredients from recipes
- [ ] Add separate items to the shopping list - t-persson/babylon#3
- [ ] Delete items from the shopping list - t-persson/babylon#3
